---
title: "African Language Sentiment"
author: "Rahim Jutha"
date: "2023-03-02"
output: html_document
---

Is making the plot about regions or counries sentiment appropriate for this data?
I think the plto should be about the sentiment of each language to hopefully show he possible nuances of the language.

# Load Packages
```{r}
library(tidyverse)
library(ggforce)
library(ggsci)
library(glue)
library(ggtext)
library(forcats)
library(showtext)
```

# Load Data
```{r}
afrisenti <- read_csv("data/afrisenti.csv")
country_regions <- read_csv("data/country_regions.csv")
language_countries <- read_csv("data/language_countries.csv")
language_scripts <- read_csv("data/language_scripts.csv")
languages <- read_csv("data/languages.csv")
```

# Load Font
```{r}
font_add_google(name = "Roboto Condensed", family = "Roboto Condensed")
font_add_google(name = "Bebas Neue", family = "Bebas Neue")
showtext_auto()
```

# Data Wrangling
```{r}
country_info <-
  language_countries %>%
  left_join(country_regions, by = "country") %>%
  filter(
    !(country == "Mozambique" & region %in% c("Southern Africa", "East Africa"))
  ) %>%
  group_by(language_iso_code) %>%
  mutate(countries = paste0(country, collapse = " ")) %>%
  select(-country) %>%
  distinct() %>%
  filter(
    !((language_iso_code %in% c("swa", "tso", "pt-MZ")) &
    (region %in% c("Southern Africa", "East Africa")))
  ) %>%
  mutate(region = case_when(
    region == "Northern Africa" ~ "North Africa",
    TRUE ~ region
  ))
  
df <-
  afrisenti %>%
  group_by(language_iso_code) %>%
  mutate(total = n()) %>%
  group_by(language_iso_code, label) %>%
  summarise(total = n() / total) %>% 
  distinct() %>%
  left_join(languages, by = "language_iso_code") %>%
  left_join(country_info, by = "language_iso_code") %>%
  
  mutate(
    lang_country = glue(
      "<span style=font-size:11pt; color:grey20>**{language}**</span><br><span style=color:grey30>{countries}</span>"),
    label = factor(label, levels = c("negative", "neutral", "positive")),
    region = factor(region, levels = c(
      "North Africa",
      "East Africa",
      "Southeastern Africa",
      "West Africa")
    )
  )
```

# Bar Plot
```{r}
ggplot(data = df, aes(x = total, y = lang_country, fill = label)) +
  geom_col() +
  scale_fill_npg() +
  facet_col(~region, scales = "free_y" ,space = "free") +
  scale_x_continuous(
    expand = c(0, 0),
    labels = scales::percent) +
  
  theme_minimal(base_family = "Roboto Condensed") +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    axis.text.y = element_markdown(),
    plot.caption = element_markdown(),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    strip.text = element_text(face = "bold", hjust = 0, color = "grey10", size = 12),
    panel.spacing = unit(1, "lines"),
    plot.background = element_rect(fill = "#FBE8C7", colour = "#FBE8C7"),
    plot.margin = margin(20,20,20,20)
  ) +
  
  guides(
    fill = guide_legend(reverse = TRUE)
  ) +
  
  labs(
    title = "African Language Sentiment Analysis",
    subtitle = "The proportion of African Language tweets with positive, neutral, and negative sentiment.",
    x = NULL,
    y = NULL,
    fill = NULL,
    caption = "Source: <b>AfriSenti: Sentiment Analysis dataset for 14 African languages</b> | Graphic by <b>Rahim Jutha</b>"
  ) -> x


ggsave(
    plot = x, filename = "test.svg",
    width = 9, height = 11, units = "in"
)
```
